# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.java.home=C:/Users/Kilian Mayrhofer/.gradle/jdks/eclipse_adoptium-25-amd64-windows.2

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version=1.1.0+26.2
maven_group=net.lordkipama.modernminecarts
archives_base_name=modernminecarts

# Dependencies
fabric_version=0.154.2+26.2
fabric_rendering_v1_version=25.3.1+6988455e9e
